modified strings and intents
kehitysto/coaching-chatbot pull request #349
Opened 2017-11-20 14:47 UTC by jope25

2017-11-20 14:48 UTC, madkoppa approved these changes

2017-11-20 15:15 UTC, veituomi commented on test/ft/invalid-input-tests.js
> +              buildResponse('@GREETING_1'),
Fix indentation

2017-11-20 15:16 UTC, veituomi requested changes
Fix indentation

2017-11-21 07:59 UTC, leppaott approved these changes

2017-11-21 08:13 UTC, veituomi approved these changes

2017-11-21 08:14 UTC, veituomi requested changes

2017-11-21 08:14 UTC, veituomi commented on test/ft/invalid-input-tests.js
>                buildResponse('@GREETING_1'),
Fix more

2017-11-21 08:23 UTC, veituomi approved these changes

2017-11-21 08:28 UTC, merged