Enable continuous deployment from dev branch to staging
kehitysto/coaching-chatbot pull request #53
Opened 2017-02-11 17:34 UTC by ascense

2017-02-12 09:04 UTC, lex requested changes
need snakes removes from scripts/write-env.js

2017-02-13 08:01 UTC, SebaSeba approved these changes

2017-02-13 08:08 UTC, mAAstro7 approved these changes

2017-02-13 08:35 UTC, lex approved these changes

2017-02-13 08:35 UTC, aqyakush approved these changes

2017-02-13 08:35 UTC, merged